# frozen_string_literal: true
source "https://rubygems.org"
ruby "4.0.2"

gemspec

gem "benchmark-ips", "~> 2.14"
gem "diff-lcs", "~> 1.5"

group :development do
  gem "debug", "~> 1.9"
  gem "minitest", "~> 5.25"
  gem "rake", "~> 13.2"
end
